//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoverallsShop.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderHasProduct = new HashSet<OrderHasProduct>();
        }
    
        public int ArticleNumber { get; set; }
        public Nullable<int> NameId { get; set; }
        public Nullable<int> CurrentDiscount { get; set; }
        public Nullable<int> CategoryItemId { get; set; }
        public Nullable<int> CountProductStock { get; set; }
        public string Discription { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Prise { get; set; }
    
        public virtual CategoryItem CategoryItem { get; set; }
        public virtual NameProduct NameProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHasProduct> OrderHasProduct { get; set; }
    }
}
